### PR TITLE
Resize property added

### LINKED ISSUE #4: Resizable editors
There are currently three editors: source code, input and output editor. Each of them cannot be resized.

It would be great if each editor could be resized. Source code editor in up/down direction, and input and output editor in left/right direction.

### PR DESCRIPTION
**Pull request by manaswinidas**
Fixes #4 
Resizable editors in the required directions added

### CODE REVIEW

**Comment by hermanzdosilovic** [comment]
Hey @manaswinidas,

I don't think this solves #4. Take a look what happens when I resize input editor to the left.
screenshot from 2017-10-07 13-53-26

This should work as on [Try Kotlin](https://try.kotlinlang.org) for example. You can easily see that you can resize each editor because your cursor changes.

Can you please fix this?

Let me know if you need more instructions on this issue.

**Comment by manaswinidas** [comment]
I think @PallaviDas07 has solved the label inconsistency issue up to some extent. The input and output editors seem to be replicated due to CodeMirror-gutter. How can it be resolved

**Comment by hermanzdosilovic** [comment]
Take a look at [cm-resize](https://github.com/Sphinxxxx/cm-resize). Before using cm-resize, you should probably remove all `height` and `min-height` attributes from `#sourceEditor`, `#inputEditor` and `#outputEditor`.

Let me know if I can help you more.

**Comment by manaswinidas** [comment]
cm-resize needs to be added in ide.js, right? After adding cm-resize I am facing the following issue.
screenshot from 2017-10-07 21-08-11

**Comment by hermanzdosilovic** [comment]
cm-resize should be downloaded and added to `js/cm-resize.js`. After that it should be included in `index.html` like [download.js](https://github.com/judge0/ide/blob/master/index.html#L36) for example. After that you can use cm-resize in `js/ide.js`.

If you take a look at [cm-resize.js](https://github.com/Sphinxxxx/cm-resize/blob/master/src/cm-resize.js#L2-L7) you can see that you can give cmResize method some config, for example:
```
cmResize(sourceEditor, {
  resizableWidth: false
});
```

I suggest that you consider my comments in previews comment I made and that you also undo your changes with labels.

Let me know if you need any more help with this. :smile:

**Pull request closed without merging**
